### ISSUE TITLE
Reduce column spam on landing page

### ISSUE THREAD

**Issue by dotfortun** [mcglauflins/Final-JobBots#16]
`<div class="container container"><div class="row flex flex-row justify-content-center"><div class="welcome col align-self-center col-sm-4"><img src="/bot-dialogue.png"></div></div><div class="row"><div class="robot col"><img src="/Robot.png"></div><div class="colHead col"><h3 class="header1">Job Applications</h3></div></div><div class="rowHead row"><div class="col"></div><div class="colHead1 col"><h1 class="header2">Simplified</h1></div></div><div class="row"><div class="col"></div><div class="col"></div><div class="colHead col"><button class="btn1">Start Here!</button></div></div></div>`

Example in HTML for the welcome bubble.

**Comment by dotfortun** [comment]
```
.welcome {
    width: 33%;
    height: calc(33vw*3/5);
    background: linear-gradient(90deg, #fff 50%, #06d 50%);
    border-radius: 50%;
    z-index: 10;
}

.welcome:after {
    content: "";
    display: block;
    position: relative;
    top: calc(33vw*3.25/6);
    left: calc(33%/2);
    width: 0;
    border-width: 45px 15px 0;
    border-style: solid;
    border-color: #FFF transparent;
    transform: rotate(30deg);
}
```

**Comment by mcglauflins** [comment]
fix issue 16

**Comment by dotfortun** [comment]
https://gist.github.com/dotfortun/75ff4bde2eb77565f7da0970aad60a3e

**Comment by dotfortun** [comment]
.robo-bg {
    background-image: url(/Robot.png);
    background-repeat: no-repeat;
    background-position: bottom left;
}
